In [167]:
import pandas as pd
from sklearn.neighbors import NearestNeighbors as KNN
from sklearn.preprocessing import MinMaxScaler
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

data_spotify = pd.read_csv('spotify_songs.csv')
data_spotify.drop_duplicates(subset=['track_name', 'track_artist'], inplace=True)
data_spotify.head()

                 track_id  ... duration_ms
0  6f807x0ima9a1j3VPbc7VN  ...      194754
1  0r7CVbZTWZgbTCYdfa2P31  ...      162600
2  1z1Hg7Vb0AhHDiEmnDE79l  ...      176616
3  75FpbthrwQmzHlBJLuGdC7  ...      169093
4  1e8PAfcKUYoKkxPhrHqw4x  ...      189052

[5 rows x 23 columns]

In [150]:
song_title = 'tough love'

In [165]:
def search_songs(user_title, top_n=1):
    vectorizer = TfidfVectorizer()
    
    titles = data_spotify['track_name'].str.lower()
    titles = titles.dropna()
    
    vectorized_titles = vectorizer.fit_transform(titles)
    user_title_vectorized = vectorizer.transform([user_title.lower()])
    
    similarities = cosine_similarity(user_title_vectorized, vectorized_titles).flatten()
    top_indices = np.argsort(similarities)[::-1][:top_n]
    
    return data_spotify.iloc[top_indices][['track_name', 'track_artist']]
similar = search_songs(song_title)
similar_title = similar['track_name'].iloc[0]
similar

                               track_name track_artist
8  Tough Love - Tiësto Remix / Radio Edit       Avicii

In [169]:
def recommend_songs(liked_song=similar_title, n_recommendations=5):
    scaler = MinMaxScaler()
    imputer = SimpleImputer(strategy='most_frequent')

    num_cols = [name for name, values in data_spotify.items() if (values.dtype == int) | (values.dtype ==                                                                                                float)]

    X_scaled = scaler.fit_transform(data_spotify[num_cols])

    X_num = pd.DataFrame(X_scaled, columns=num_cols)

    genre_dummies = pd.get_dummies(data_spotify['playlist_genre'], dtype=int)
    subgenre_dummies = pd.get_dummies(data_spotify['playlist_subgenre'], dtype=int)

    genre_dummies_df = pd.DataFrame(imputer.fit_transform(genre_dummies), columns = genre_dummies.columns)
    subgenre_dummies_df = pd.DataFrame(imputer.fit_transform(subgenre_dummies), columns =                       subgenre_dummies.columns)

    X = pd.concat([X_num, genre_dummies_df, subgenre_dummies_df], axis=1)

    model = KNN(metric='cosine')
    model.fit(X)

    def find_id(name):
        track_index = data_spotify[data_spotify['track_name'] == name].index
        return track_index

    song_index = find_id(liked_song)

    distance, indices = model.kneighbors(X.iloc[song_index], n_neighbors=(n_recommendations + 1))
    indices = indices[0, :]
    results = data_spotify.iloc[indices]
    results = results[results['track_name'] != liked_song]
    results_titles = results[['track_name', 'track_artist', 'track_album_name']]
    return results_titles
recommend_songs()

                                     track_name  ...                  track_album_name
177  Call You Mine - Asketa & Natan Chaim Remix  ...       Call You Mine - The Remixes
243               High Hopes - Don Diablo Remix  ...     High Hopes (Don Diablo Remix)
308            Think About You - Galantis Remix  ...  Think About You (Galantis Remix)
500                    I Could Get Used To This  ...          I Could Get Used To This
495                                   SHA LA LA  ...                          Genie:us

[5 rows x 3 columns]